spring.application.name=SpringDataJpa1



spring.datasource.url=jdbc:mysql://localhost:3306/"your data base name"
spring.datasource.username="by default name is "root" but if you have another name use that name only"
spring.datasource.password="your database password"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver




#user 


# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
